=== curiousTauseef/warehouse-2/Warehouse.Component/Printing/FormObjectTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Forms">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Form"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Form">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Section"/>
      </xs:sequence>
      <xs:attribute name="formName" use="required" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Section">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="type" type="sectionType"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HBox">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="BoxItem"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="VBox">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="BoxItem"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BoxItem">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rectangle">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="fill" default="false" type="xs:boolean"/>
      <xs:attribute name="fillcolor" type="xs:string" default="#000000"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TextBox">
    <xs:complexType>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="format" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HLine">
    <xs:complexType>
      <xs:attribute name="length" type="xs:float"/>
      <xs:attribute name="thickness" type="xs:float"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="VLine">
    <xs:complexType>
      <xs:attribute name="length" type="xs:float"/>
      <xs:attribute name="thickness" type="xs:float"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Table">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Columns" minOccurs="0"/>
        <xs:element ref="Rows" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="sourceTable" type="xs:string"/>
      <xs:attribute name="sourceTableHasFooter" type="xs:boolean"/>
      <xs:attribute name="sourceTableHasFooterSource" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="headerStyle" type="xs:string"/>
      <xs:attribute name="footerStyle" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Columns">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Column"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Column">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Template" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="Header" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="Footer" maxOccurs="1" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="sourceType" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Template">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Header">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="sourceType" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Footer">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="sourceType" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rows">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Row"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Row">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Cell"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cell">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="sectionType">
    <xs:annotation>
      <xs:documentation>Section types</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="General">
        <xs:annotation>
          <xs:documentation>This section contains general content</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PageHeader">
        <xs:annotation>
          <xs:documentation>This section will be shown on the top of each page</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PageFooter">
        <xs:annotation>
          <xs:documentation>This section will be shown on the bottom of each page</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PageBreak">
        <xs:annotation>
          <xs:documentation>This section will move all the content after it to the next page</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== curiousTauseef/warehouse-2/Warehouse.Component/Printing/Report.xml
<?xml version="1.0"?>
<Form formName="Report" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///e:/Projects/Work/Warehouse/Warehouse.Component/Documenting/FormObjectTemplate.xsd">
  <Section type="PageHeader">
    <HBox style="width:100%;height:50">
      <TextBox sourceFormat="dateFormat" sourceField="reportDate" font="size:10" style="valign:center;height:100%;hfill:true"/>
      <TextBox sourceField="reportName" font="size:14" style="valign:center;halign:center;width:100%;height:100%"/>
      <HBox style="width:80px"/>
    </HBox>
  </Section>
  <Section>
    <Table sourceTable="reportDetails" sourceTableHasFooterSource="reportHasFooter" style="width:100%" />
  </Section>
  <Section type="PageFooter">
    <HBox style="width:100%;height:50">
      <TextBox sourceField="productId" font="size:8;italic:true" style="valign:center;halign:left;width:100%;height:100%"/>
      <HBox style="valign:center;hpadding:10;hfill:true;height:100%;halign:right">
        <TextBox sourceFormat="currentPageFormat" sourceField="%CurrentPage%" font="size:8" />
        <TextBox sourceFormat="totalPagesFormat" sourceField="%TotalPages%" font="size:8" style="hpadding:2"/>
      </HBox>
    </HBox>
  </Section>
</Form>

=== curiousTauseef/warehouse-2/Warehouse.Component/Documents/Armenia/CashReceipt.xml
<?xml version="1.0"?>
<Form formName="CashReceipt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///e:/Projects/Work/Warehouse/Warehouse.Component/Documenting/FormObjectTemplate.xsd">
  <Section>
    <VBox style="width:100%">
      <TextBox sourceField="ReceiptTitle" style="width:100%;halign:center" font="size:11;bold:true" trimming="ellipsischaracter"/>
      <Table style="width:100%;vfill:true;innerborder:0;border:0;halign:center" sourceTable="HeaderDetails">
        <Columns>
          <Column style="width:100%;halign:center" font="size:8" trimming="ellipsischaracter" sourceField="">
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
      <TextBox sourceField="ReceiptLabel" style="width:100%;halign:center" font="size:11;bold:true;vpadding:10" trimming="ellipsischaracter"/>
      <HLine thickness="2" style="width:100%" />
      <HBox style="height:10" />
      <HBox style="width:100%;halign:center">
        <TextBox sourceField="DateValue" font="size:8" style="width:100%"/>
	<TextBox sourceField="TimeValue" font="size:8" style="width:1%;hfill:true"/>
      </HBox>
      <Table style="width:100%;vfill:true;innerborder:0;border:0;vpadding:0;halign:center" sourceTable="FreeText">
        <Columns>
          <Column style="width:100%;halign:left" font="size:8" trimming="ellipsischaracter" sourceField="">
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
    </VBox>
  </Section>
  <Section style="vpadding:5">
    <HLine thickness="1" style="width:100%" />
	<Table style="innerborder:0;border:0;width:100%" headerStyle="width:100%;vfill:true;" sourceTable="Details">
      <Columns>
        <Column>
          <Template style="width:100%">
            <VBox>
              <HBox>
                <TextBox sourceField="GoodsName" style="width:100%" font="size:8;bold:true:underline:true" trimming="ellipsischaracter" wrap="true" />
                <TextBox sourceField="GoodsCode" font="size:6;underline:true" style="width:1%;hfill:true"/>
              </HBox>
              <HBox style="innerspacing:2">
                <HBox style="width:100%"/>
                <TextBox sourceField="Quantity" font="size:8" style="width:1%;hfill:true"/>
                <TextBox sourceField="MUnit" font="size:8" style="width:1%;hfill:true"/>
                <TextBox text="x" font="size:8" style="width:1%;hfill:true"/>
                <TextBox sourceField="Price" font="size:8" style="width:1%;hfill:true"/>
                <TextBox text="=" font="size:8" style="width:1%;hfill:true"/>
                <TextBox sourceField="Total" font="size:8" style="width:1%;hfill:true"/>
              </HBox>
              <HBox style="innerspacing:2">
                <HBox style="width:100%"/>
                <TextBox sourceField="Discount" font="size:8" style="width:1%;hfill:true"/>
              </HBox>
	      <HLine thickness="1" style="width:100%" />
            </VBox>
          </Template>
          <Header />
          <Footer />
        </Column>
      </Columns>
    </Table>
  </Section>
  <Section style="vpadding:8">
    <VBox>
      <HBox style="width:100%">
        <TextBox sourceField="SubTotalLabel" font="size:8;bold:true" style="width:100%"/>
        <TextBox sourceField="SubTotalValue" font="size:8;bold:true" style="width:1%;hfill:true"/>
      </HBox>
      <HBox style="width:100%">
        <TextBox sourceField="TotalDiscountLabel" font="size:8;bold:true" style="width:100%"/>
        <TextBox sourceField="TotalDiscountValue" font="size:8;bold:true" style="width:1%;hfill:true"/>
      </HBox>
      <HBox style="width:100%">
        <TextBox sourceField="TotalLabel" font="size:11;bold:true" style="width:100%"/>
        <TextBox sourceField="TotalValue" font="size:11;bold:true" style="width:1%;hfill:true"/>
      </HBox>
      <HBox style="width:100%">
        <TextBox sourceField="TotalVATLabel" font="size:9" style="width:100%" />
        <TextBox sourceField="TotalVATValue" font="size:9" />
      </HBox>
      <HBox style="width:100%">
        <TextBox sourceField="TotalNetAmountLabel" font="size:9" style="width:100%" />
        <TextBox sourceField="TotalNetAmountValue" font="size:9" />
      </HBox>
      <Table style="width:100%;innerborder:0;border:0" headerStyle="width:100%;" sourceTable="PaymentValues">
        <Columns>
          <Column>
            <Template style="width:100%">
              <VBox>
                <HBox style="innerspacing:2;width:100%">
                  <TextBox sourceField="Key" font="size:8" style="width:100%"/>
                  <TextBox sourceField="Value" font="size:8" style="width:1%;hfill:true"/>
                </HBox>
              </VBox>
            </Template>
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
    </VBox>
  </Section>
  <Section>
    <VBox>
      <Table style="width:100%;vfill:true;innerborder:0;border:0" sourceTable="FooterDetails">
        <Columns>
          <Column style="width:100%;halign:center;vpadding:4" font="size:8" sourceField="">
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
      <TextBox text="--------------------" font="size:9" style="width:100%" />
      <Picture sizeMode="Fit" style="xstart:10;width:20;height:10" resource="Warehouse.Hardware.Vladster;Logo.png" />
      <HBox style="height:10" />
    </VBox>
  </Section>
</Form>

=== curiousTauseef/warehouse-2/Warehouse.Component/Documents/Armenia/KitchenReceipt.xml
<?xml version="1.0"?>
<Form formName="KitchenReceipt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///e:/Projects/Work/Warehouse/Warehouse.Component/Documenting/FormObjectTemplate.xsd">
  <Section>
    <VBox style="width:100%">
      <TextBox sourceField="ReceiptTitle" style="width:100%;halign:center" font="size:11;bold:true" trimming="ellipsischaracter"/>
      <Table style="width:100%;vfill:true;innerborder:0;border:0;halign:center" sourceTable="HeaderDetails">
        <Columns>
          <Column style="width:100%;halign:center" font="size:8" trimming="ellipsischaracter" sourceField="">
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
      <TextBox sourceField="ReceiptLabel" style="width:100%;halign:center" font="size:11;bold:true" trimming="ellipsischaracter"/>
      <HBox style="width:100%;halign:center">
        <TextBox sourceField="DateValue" font="size:8" style="width:100%"/>
        <TextBox sourceField="TimeValue" font="size:8" style="width:1%;hfill:true"/>
      </HBox>
      
      <Table style="width:100%;vfill:true;innerborder:0;border:0;halign:center" sourceTable="FreeText">
        <Columns>
          <Column style="width:100%;halign:left" font="size:8" trimming="ellipsischaracter" sourceField="">
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
      <Table style="width:100%;vfill:true;innerborder:0;border:0;halign:center" sourceTable="FreeKeyValueText">
        <Columns>
          <Column style="width:100%;halign:left" font="size:8" trimming="ellipsischaracter" sourceField="Key">
            <Header />
            <Footer />
          </Column>
          <Column style="width:100%;halign:right" font="size:8" trimming="ellipsischaracter" sourceField="Value">
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
    </VBox>
  </Section>
  <HBox style="height:10"/>
  <HLine thickness="1" style="width:100%" />
  <Section>
    <VBox>
      <Table style="innerborder:0;border:0;width:100%" headerStyle="width:100%;vfill:true;"
             itemStyle="width:100%;vfill:true;allowvbreak:true" sourceTable="Details">
        <Columns>
          <Column>
            <Template style="width:100%;allowvbreak:true;vpadding:4">
              <VBox>
                <TextBox sourceField="GoodsName" style="width:100%" font="size:8;underline:true;bold:true" trimming="ellipsischaracter" />
                <HBox style="innerspacing:2;allowvbreak:false">
                  <VBox style="width:100%;hfill:true;valign:top">
                    <HBox style="innerspacing:2">
                      <TextBox sourceField="Quantity" font="size:10" style="width:1%;hfill:true"/>
                      <TextBox sourceField="MUnit" font="size:10" style="width:1%;hfill:true;halign:left"/>
                    </HBox>
                    <Table style="width:100%;vfill:true;innerborder:0;border:0;vpadding:4" sourceTable="Modifiers">
                      <Columns>
                        <Column style="width:100%;halign:left" font="size:8" trimming="ellipsischaracter" sourceField="">
                          <Header />
                          <Footer />
                        </Column>
                      </Columns>
                    </Table>
                  </VBox>
                </HBox>
              </VBox>
            </Template>
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
    </VBox>
  </Section>
  <Section>
    <VBox>
      <TextBox sourceField="ModificationsLabel" style="width:100%;vpadding:2;halign:center" font="size:11;bold:true" trimming="ellipsischaracter" />
      <Table style="innerborder:0;border:0;width:100%" headerStyle="width:100%;vfill:true;"
             itemStyle="width:100%;vfill:true;allowvbreak:true" sourceTable="ModifiedDetails">
        <Columns>
          <Column>
            <Template style="width:100%;allowvbreak:true">
              <VBox>
                <TextBox sourceField="GoodsName" style="width:100%" font="size:8;underline:true;bold:true" trimming="ellipsischaracter" />
                <HBox style="innerspacing:2;allowvbreak:false">
                  <TextBox sourceField="OldModLabel" font="size:10;bold:true" style="width:1%;hfill:true"/>
                  <VBox style="width:100%;hfill:true;valign:top">
                    <HBox style="innerspacing:2">
                      <TextBox sourceField="OldQuantity" font="size:10" style="width:1%;hfill:true"/>
                      <TextBox sourceField="MUnit" font="size:10" style="width:1%;hfill:true;halign:left"/>
                    </HBox>
                    <Table style="width:100%;vfill:true;innerborder:0;border:0;vpadding:0" sourceTable="OldModifiers">
                      <Columns>
                        <Column style="width:100%;halign:left" font="size:8" trimming="ellipsischaracter" sourceField="">
                          <Header />
                          <Footer />
                        </Column>
                      </Columns>
                    </Table>
                  </VBox>
                </HBox>
                <HBox style="innerspacing:2;allowvbreak:false">
                  <TextBox sourceField="NewModLabel" font="size:10;bold:true" style="width:1%;hfill:true;valign:top"/>
                  <VBox style="width:100%;hfill:true;valign:top">
                    <HBox style="innerspacing:2">
                      <TextBox sourceField="Quantity" font="size:10" style="width:1%;hfill:true"/>
                      <TextBox sourceField="MUnit" font="size:10" style="width:1%;hfill:true;halign:left"/>
                    </HBox>
                    <Table style="width:100%;vfill:true;innerborder:0;border:0;vpadding:4" sourceTable="Modifiers">
                      <Columns>
                        <Column style="width:100%;halign:left" font="size:8" trimming="ellipsischaracter" sourceField="">
                          <Header />
                          <Footer />
                        </Column>
                      </Columns>
                    </Table>
                  </VBox>
                </HBox>
              </VBox>
            </Template>
            <Header />
            <Footer />
          </Column>
        </Columns>
      </Table>
    </VBox>
  </Section>
  <HLine thickness="1" style="width:100%" />
  <Picture sizeMode="Fit" style="xstart:10;width:20;height:10" resource="Warehouse.Hardware.Vladster;Logo.png" />
</Form>
