=== curiousTauseef/warehouse-2/Warehouse.Component/Printing/FormObjectTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Forms">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Form"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Form">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Section"/>
      </xs:sequence>
      <xs:attribute name="formName" use="required" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Section">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="type" type="sectionType"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HBox">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="BoxItem"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="VBox">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="BoxItem"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BoxItem">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rectangle">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="fill" default="false" type="xs:boolean"/>
      <xs:attribute name="fillcolor" type="xs:string" default="#000000"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TextBox">
    <xs:complexType>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="format" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HLine">
    <xs:complexType>
      <xs:attribute name="length" type="xs:float"/>
      <xs:attribute name="thickness" type="xs:float"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="VLine">
    <xs:complexType>
      <xs:attribute name="length" type="xs:float"/>
      <xs:attribute name="thickness" type="xs:float"/>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Table">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Columns" minOccurs="0"/>
        <xs:element ref="Rows" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="sourceTable" type="xs:string"/>
      <xs:attribute name="sourceTableHasFooter" type="xs:boolean"/>
      <xs:attribute name="sourceTableHasFooterSource" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="headerStyle" type="xs:string"/>
      <xs:attribute name="footerStyle" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Columns">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Column"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Column">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Template" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="Header" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="Footer" maxOccurs="1" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="sourceType" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Template">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Header">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="sourceType" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Footer">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="sourceField" type="xs:string"/>
      <xs:attribute name="sourceType" type="xs:string"/>
      <xs:attribute name="sourceFormat" type="xs:string"/>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="font" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rows">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Row"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Row">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Cell"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cell">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Rectangle"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="TextBox"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="HLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="VLine"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Table"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="style" type="xs:string"/>
      <xs:attribute name="text" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="sectionType">
    <xs:annotation>
      <xs:documentation>Section types</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="General">
        <xs:annotation>
          <xs:documentation>This section contains general content</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PageHeader">
        <xs:annotation>
          <xs:documentation>This section will be shown on the top of each page</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PageFooter">
        <xs:annotation>
          <xs:documentation>This section will be shown on the bottom of each page</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PageBreak">
        <xs:annotation>
          <xs:documentation>This section will move all the content after it to the next page</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== curiousTauseef/warehouse-2/Warehouse.Component/Printing/WasteProtocol.xml
<?xml version="1.0"?>
<Form formName="WasteProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///e:/Projects/Work/Warehouse/Warehouse.Component/Documenting/FormObjectTemplate.xsd">
  <Section style="vpadding:10">
    <VBox style="width:100%;innervspacing:10">
      <HBox style="width:100%">
        <VBox style="width:50%;height:50%;border:1">
          <TextBox sourceField="protocolTitle" font="size:14;underline:true;bold:true" style="width:100%;halign:center"/>
          <TextBox sourceField="protocolSubTitle" font="size:12;bold:true" style="width:100%;halign:center"/>
          <HBox style="width:100%;padding:7">
            <HLine thickness="1" style="width:100%" />
          </HBox>
          <HBox style="width:100%;height:100%" />
          <HBox style="width:100%;padding:7">
            <TextBox sourceField="protocolNumber" sourceFormat="numberFormat" font="size:10;bold:true" style="width:50%"/>
            <HBox style="width:15" />
            <TextBox sourceField="protocolDate" sourceFormat="dateFormat" font="size:10;bold:true" style="width:50%"/>
          </HBox>
        </VBox>
        <HBox style="width:10" />
        <Table style="width:50%;innerborder:0;innerhspacing:20" headerStyle="width:100%;vfill:true;bgcolor:#D4D0C8"
               itemStyle="width:100%;vfill:true;allowvbreak:false" footerStyle="width:100%;vfill:true;bgcolor:#D4D0C8">
          <Columns>
            <Column />
            <Column style="width:100%" />
          </Columns>
          <Rows>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="companyNameLabel" />
              </Cell>
              <Cell style="width:100%">
                <TextBox sourceField="companyName" wrap="True" font="size:8;bold:true" style="width:100%" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="companyNumberLabel" />
              </Cell>
              <Cell style="width:100%">
                <TextBox sourceField="companyNumber" wrap="True" font="size:8;bold:true" style="width:100%" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="companyCityLabel" />
              </Cell>
              <Cell style="width:100%">
                <TextBox sourceField="companyCity" wrap="True" font="size:8;bold:true" style="width:100%" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="companyAddressLabel" />
              </Cell>
              <Cell style="width:100%">
                <TextBox sourceField="companyAddress" wrap="True" font="size:8;bold:true" style="width:100%" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="companyTelephoneLabel" />
              </Cell>
              <Cell style="width:100%">
                <TextBox sourceField="companyTelephone" wrap="True" font="size:8;bold:true" style="width:100%" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="companyLiablePersonLabel" />
              </Cell>
              <Cell style="width:100%">
                <TextBox sourceField="companyLiablePerson" wrap="True" font="size:8;bold:true" style="width:100%" />
              </Cell>
            </Row>
          </Rows>
        </Table>
      </HBox>
      <TextBox sourceField="pointOfSale" sourceFormat="pointOfSaleFormat" font="size:8;bold:true" style="width:100%"/>
    </VBox>
  </Section>
  <Section style="vpadding:8">
    <Table sourceTable="protocolDetails" style="width:100%" headerStyle="width:100%;vfill:true;bgcolor:#D4D0C8" itemStyle="width:100%;vfill:true;allowvbreak:false" footerStyle="width:100%;vfill:true;bgcolor:#D4D0C8">
      <Columns>
        <Column>
          <Template style="padding:2;halign:center;valign:center;height:100%">
            <TextBox sourceField="Number" />
          </Template>
          <Header style="padding:2">
            <TextBox sourceField="detailHeaderNumber" />
          </Header>
        </Column>
        <Column>
          <Template style="padding:2;valign:center">
            <TextBox sourceField="GoodsCode" />
          </Template>
          <Header style="padding:2">
            <TextBox sourceField="detailHeaderCode" />
          </Header>
        </Column>
        <Column>
          <Template style="width:100%;padding:2;valign:center">
            <TextBox sourceField="GoodsName" wrap="true" />
          </Template>
          <Header style="width:100%;padding:2;hfill:false">
            <TextBox sourceField="detailHeaderGoods" />
          </Header>
        </Column>
        <Column>
          <Template style="padding:2;halign:center;valign:center">
            <TextBox sourceField="MUnit" />
          </Template>
          <Header style="padding:2">
            <TextBox sourceField="detailHeaderMUnit" />
          </Header>
        </Column>
        <Column>
          <Template style="padding:2;halign:right;valign:center">
            <TextBox sourceField="Quantity" />
          </Template>
          <Header style="padding:2">
            <TextBox sourceField="detailHeaderQtty" />
          </Header>
        </Column>
        <Column>
          <Template style="padding:2;halign:right;valign:center">
            <TextBox sourceField="Price" />
          </Template>
          <Header style="padding:2">
            <TextBox sourceField="detailHeaderPrice" />
          </Header>
        </Column>
        <Column>
          <Template style="padding:2;halign:right;valign:center">
            <TextBox sourceField="Total" />
          </Template>
          <Header style="padding:2">
            <TextBox sourceField="detailHeaderTotal" />
          </Header>
        </Column>
      </Columns>
    </Table>
  </Section>
  <Section>
    <VBox style="width:100%">
      <HBox style="width:100%">
        <HBox style="width:100%" />
        <Table style="border:0;innerborder:0;innerhspacing:20;hfill:true" headerStyle="width:100%;vfill:true;bgcolor:#D4D0C8"
               itemStyle="width:100%;vfill:true;allowvbreak:false" footerStyle="width:100%;vfill:true;bgcolor:#D4D0C8">
          <Columns>
            <Column />
            <Column />
          </Columns>
          <Rows>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="totalLabel" font="size:10;italic:true" />
              </Cell>
              <Cell style="halign:right">
                <TextBox sourceField="total" font="size:10;bold:true" style="halign:right" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="vatLabel" font="size:10;italic:true" />
              </Cell>
              <Cell style="halign:right">
                <TextBox sourceField="vat" font="size:10;bold:true" style="halign:right" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell />
              <Cell style="height:7;valign:center">
                <HLine thickness="2" style="width:100%" />
              </Cell>
            </Row>
            <Row style="innervborder:0;spacing:0;innerhspacing:20">
              <Cell>
                <TextBox sourceField="totalPlusVatLabel" font="size:10;italic:true" />
              </Cell>
              <Cell style="halign:right">
                <TextBox sourceField="totalPlusVat" font="size:10;bold:true" style="halign:right" />
              </Cell>
            </Row>
          </Rows>
        </Table>
      </HBox>
      <HBox style="width:100%;vpadding:10">
        <TextBox sourceField="totalInWordsLabel" font="size:10;underline:false;bold:false;italic:true" />
        <TextBox sourceField="totalInWords" font="size:10;underline:false;bold:true;italic:false" wrap="true" style="width:100%;height:100%" />
      </HBox>
      <VBox style="width:100%;height:100%;vpadding:20">
        <TextBox sourceField="noteLabel" font="underline:true;bold:true;italic:false" />
        <TextBox sourceField="note" style="vpadding:4" />
      </VBox>
      <HBox style="width:100%">
        <HBox style="width:100%;hfill:true">
          <TextBox sourceField="recipientSignLabel" font="size:10;bold:true" />
          <HLine style="width:100%;height:100%;valign:bottom" />
        </HBox>
        <BoxItem style="width:10;height:100%" />
        <HBox style="width:100%;hfill:true">
          <TextBox sourceField="creatorSignLabel" font="size:10;bold:true" />
          <HLine style="width:100%;height:100%;valign:bottom" />
        </HBox>
      </HBox>
    </VBox>
  </Section>
  <Section type="PageFooter">
    <HBox style="width:100%;height:50">
      <TextBox sourceField="productId" font="size:8;italic:true" style="width:100%;height:100%;valign:center"/>
      <HBox style="width:100%;valign:center;height:100%;hpadding:10;hfill:true;halign:right">
        <TextBox sourceField="%CurrentPage%" sourceFormat="currentPageFormat"/>
        <TextBox sourceField="%TotalPages%" sourceFormat="totalPagesFormat" style="hpadding:2"/>
      </HBox>
    </HBox>
  </Section>
</Form>
